# ConsoleCommands by @ImCur_ / @Man297
# Github: https://github.com/MessyCraft/ConsoleCommands/

# Basic config / 基础配置

# The maximum limit of /loopcmd can provide(-1 to disable limit, 0 or make it empty to disable this function)
# (Some command takes a lot of performance impact - do not assume your server can hold that!)
# /loopcmd 所能提供的最高循环次数 设为-1表示不限制 留空或设为0表示禁用
# (某些命令占用巨大,不要过于高估服务器性能)
times_limit: 100


# Security configuration / 安全配置

# Whether to allow this plugin to execute LuckPerms command as console or player
# If allowed, player that have ConsoleCommands permission can access LuckPerms to get permissions for entire Bungeecord server!
# if your server is not a Bungeecord server or not having LuckPerms, you can ignore this config.
# 是否允许本插件以控制台/玩家的身份执行 LuckPerms 命令 默认禁止
# 有可能获得整个 BungeeCord 群组服的权限, 没有 Bungeecord 或没有 LuckPerms 的服务器请忽视
allow_lp_command: false

# List of commands that cannot be executed on the server console
# 禁止在服务器控制台执行的命令列表
bannedcmd_asconsole:
  - ExampleDangerousCommand

# List of commands that cannot be executed on the player
# 禁止在服务器玩家执行的命令列表
bannedcmd_asplayer:
  - ExampleDangerousCommand
